# Generated by Django 3.1.7 on 2021-03-08 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('containsProteins', models.BooleanField(default=False)),
                ('containsFish', models.BooleanField(default=False)),
                ('containsVegetables', models.BooleanField(default=False)),
                ('isMainCourse', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSelected', models.DateTimeField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=100)),
                ('containsProteins', models.BooleanField(default=False)),
                ('containsFish', models.BooleanField(default=False)),
                ('containsVegetables', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.food')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidName', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealName', models.CharField(max_length=100)),
                ('mealComposition', models.ManyToManyField(to='kidsbackendapp.FoodConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.IntegerField()),
                ('weekDay', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('mealTime', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.meal')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-3)])),
                ('comment', models.TextField()),
                ('foodOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.foodoption')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.kid')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.food')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.kid')),
            ],
        ),
        migrations.AddField(
            model_name='foodconfiguration',
            name='mealOption',
            field=models.ManyToManyField(to='kidsbackendapp.FoodOption'),
        ),
    ]
