# Generated by Django 3.1.7 on 2021-10-02 08:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('containsProteins', models.BooleanField(default=False)),
                ('containsFish', models.BooleanField(default=False)),
                ('containsVegetables', models.BooleanField(default=False)),
                ('isMainCourse', models.BooleanField(default=True)),
                ('lastEaten', models.DateTimeField(blank=True, null=True)),
                ('foodImage', models.ImageField(blank=True, default=None, null=True, upload_to='recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidName', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='kidsbackendapp.food')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_details', to='kidsbackendapp.kid')),
            ],
        ),
        migrations.CreateModel(
            name='DateMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mealTime', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('customization', models.CharField(max_length=100)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='kidsbackendapp.food')),
            ],
        ),
    ]
