# Generated by Django 3.1.7 on 2021-03-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodconfiguration',
            old_name='mealOption',
            new_name='foodOption',
        ),
        migrations.AddField(
            model_name='foodconfiguration',
            name='foodConfigurationName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodconfiguration',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsbackendapp.food'),
        ),
    ]
