# Generated by Django 3.1.7 on 2021-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0002_auto_20210308_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoreOptions',
            new_name='ScoreOption',
        ),
        migrations.AlterField(
            model_name='food',
            name='isMainCourse',
            field=models.BooleanField(default=True),
        ),
    ]
