# Generated by Django 3.1.7 on 2021-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0004_auto_20210308_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoption',
            name='food',
        ),
        migrations.RemoveField(
            model_name='scoreoption',
            name='foodOption',
        ),
        migrations.RemoveField(
            model_name='scoreoption',
            name='kid',
        ),
        migrations.AddField(
            model_name='food',
            name='lastEaten',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealComposition',
            field=models.ManyToManyField(to='kidsbackendapp.Food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FoodConfiguration',
        ),
        migrations.DeleteModel(
            name='FoodOption',
        ),
        migrations.DeleteModel(
            name='ScoreOption',
        ),
    ]
