# Generated by Django 3.1.7 on 2021-03-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0005_auto_20210309_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekmenu',
            name='meal',
        ),
        migrations.AddField(
            model_name='weekmenu',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='kidsbackendapp.Food'),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
