# Generated by Django 3.1.7 on 2021-04-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0006_auto_20210309_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='kidsbackendapp.food'),
        ),
        migrations.AlterField(
            model_name='score',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_details', to='kidsbackendapp.kid'),
        ),
    ]
