# Generated by Django 3.1.7 on 2021-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0007_auto_20210420_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodImage',
            field=models.ImageField(null=True, upload_to='recipes'),
        ),
    ]
