# Generated by Django 3.1.7 on 2021-05-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0008_food_foodimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mealTime', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('customization', models.CharField(max_length=100)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='kidsbackendapp.food')),
            ],
        ),
    ]
