# Generated by Django 3.1.7 on 2021-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0009_datemenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes'),
        ),
    ]
