# Generated by Django 3.1.7 on 2021-06-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsbackendapp', '0010_auto_20210605_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekMenu',
        ),
    ]
